package info.androidhive.firebase.common;


public interface IGoogleTrackingKeys {
    String LOGIN_ID = "GOOGLE_TRACKING_ANDROID_LOGIN";
    String CREATE_ACCOUNT_ID = "GOOGLE_TRACKING_ANDROID_CREATE_ACCOUNT";
    String ACTIVATE_ACCOUNT_ID = "GOOGLE_TRACKING_ANDROID_ACTIVATE_ACCOUNT";
    String FORGOT_PASSWORD_ID = "GOOGLE_TRACKING_ANDROID_FORGOT_PASSWORD";
    String SUMMARY_ID = "GOOGLE_TRACKING_ANDROID_SUMMARY";
    String BALANCE_ID = "GOOGLE_TRACKING_ANDROID_BALANCE";
    String PROFILE_ID = "GOOGLE_TRACKING_ANDROID_PROFILE";
    String MAP_ID = "GOOGLE_TRACKING_ANDROID_MAP";
    String LIST_ID = "GOOGLE_TRACKING_ANDROID_LIST";
    String FAVORITE_ID = "GOOGLE_TRACKING_ANDROID_FAVORITE";
    String CURRENT_CHARGE_ID = "GOOGLE_TRACKING_ANDROID_CURRENT_CHARGE";
    String CHARGE_HISTORY_ID = "GOOGLE_TRACKING_ANDROID_CHARGE_HISTORY";
    String ONGOING_PROMOTION = "GOOGLE_TRACKING_ANDROID_ONGOING_PROMOTION";
    String SPOT_PROMOTION = "GOOGLE_TRACKING_ANDROID_SPOT_PROMOTION";
    String CHARGER_LIST_ID = "GOOGLE_TRACKING_ANDROID_CHARGER_LIST";
}
